/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {

 "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "myAPI",
            "endpoint": "https://l0sqt7a9v0.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],

};


export default awsmobile;
